export const data = {
  cpu_usage: 75.3,
  ram_usage: 87.8,
  cpu_temperature: 68,
  disk_health: 85,
  free_disk_space: 94,
  total_disk_space: 240,
};

export const historyData = [
  {
    cpu_usage: 40,
    ram_usage: 86,
    cpu_temperature: 65,
    disk_health: 80,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Sab",
  },
  {
    cpu_usage: 95,
    ram_usage: 35,
    cpu_temperature: 80,
    disk_health: 65,
    free_disk_space: 80,
    total_disk_space: 240,
    day: "Ter",
  },
  {
    cpu_usage: 70,
    ram_usage: 92,
    cpu_temperature: 85,
    disk_health: 60,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Dom",
  },
  {
    cpu_usage: 80,
    ram_usage: 65,
    cpu_temperature: 70,
    disk_health: 75,
    free_disk_space: 110,
    total_disk_space: 240,
    day: "Seg",
  },
  {
    cpu_usage: 30,
    ram_usage: 70,
    cpu_temperature: 75,
    disk_health: 70,
    free_disk_space: 160,
    total_disk_space: 240,
    day: "Sab",
  },
  {
    cpu_usage: 81,
    ram_usage: 48,
    cpu_temperature: 80,
    disk_health: 65,
    free_disk_space: 80,
    total_disk_space: 240,
    day: "Seg",
  },
  {
    cpu_usage: 70,
    ram_usage: 92,
    cpu_temperature: 85,
    disk_health: 60,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Ter",
  },
  {
    cpu_usage: 95,
    ram_usage: 35,
    cpu_temperature: 80,
    disk_health: 65,
    free_disk_space: 80,
    total_disk_space: 240,
    day: "Qua",
  },
  {
    cpu_usage: 70,
    ram_usage: 92,
    cpu_temperature: 85,
    disk_health: 60,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Qui",
  },
  {
    cpu_usage: 81,
    ram_usage: 48,
    cpu_temperature: 80,
    disk_health: 65,
    free_disk_space: 80,
    total_disk_space: 240,
    day: "Sex",
  },
  {
    cpu_usage: 70,
    ram_usage: 92,
    cpu_temperature: 85,
    disk_health: 60,
    free_disk_space: 120,
    total_disk_space: 240,
    day: "Dom",
  },
];
